### ISSUE TITLE
Link-tos in navbar doesn't set the active class in the right place

### ISSUE THREAD

**Issue by RiccardoDalFiume** [balinterdi/rarwe-issues#16]
When using
```html
<ul class="nav navbar-nav">
    <li>{{link-to "Bands" "bands"}}</li>
    <li>{{link-to "Songs" "songs"}}</li>
</ul>
```
the `active` class is applied to the `a` element, not to `li`, thus is not shown by Bootstrap as an active page.

I had to use this
```html
{{#link-to "index" tagName="li" }}
    <a {{bind-attr href="view.href" }}>Bands</a>
{{/link-to}}
```

**Comment by balinterdi** [comment]
Thank you, Riccardo.

I have used the following css to achieve the same effect:

```css
.nav-tabs > li > a.active,
.nav-tabs > li > a.active:hover,
.nav-tabs > li > a.active:focus {
  color: #555;
  cursor: default;
  background-color: #fff;
  border: 1px solid #ddd;
  border-bottom-color: transparent;
}
```

I'd already updated the book to include that css snippet so that people with only the book can also see the active links. This will be part of the next (point) release of the book.
