### ISSUE TITLE
Duplicated css in templates and nested routes chapters

### ISSUE THREAD

**Issue by jluckyiv** [balinterdi/rarwe-issues#169]
I'm using a new epub reader, so I'm not sure of the pages, but the following css is duplicated in `app.css` in the **templates and bindings** chapter and the **nested routes** chapter (20160324 release). 

```css
.songs .rating {
  color: #aaa;
  font-size: 1.1em;
}
```

Also, I think the last screen shot in the **routing** chapter is incorrect because it has black numbers for the song ratings, so it probably has to be updated to show that the css was changed in the previous chapter.
