### ISSUE TITLE
CSS bug in sidebar rule

### ISSUE THREAD

**Issue by balinterdi** [balinterdi/rarwe-issues#301]
The book has the following snippet on page 51:

```css
 .rr-sidebar {
   float: left;
   width: calc( 100% / 3 ); /* .w-third */
};
```

The closing semicolon closes the following rule not to be applied and it might cause the template not to be rendered correctly.
