### ISSUE TITLE
Chapter 8 - CSS Weirdness

### ISSUE THREAD

**Issue by jagthedrummer** [balinterdi/rarwe-issues#312]
Disclaimer : I've been trying to follow everything exactly as it's presented, but it's _entirely_ possible that I've missed/screwed-up something along the way that got my CSS into a weird state.

In Chapter 8 by page 129 my app doesn't match the screen shot:

<img width="827" alt="screen shot 2018-05-02 at 8 25 54 pm" src="https://user-images.githubusercontent.com/58702/39556610-25446700-4e47-11e8-9d60-94a0a3290673.png">

In addition to the visual difference, the top couple bands in the menu are un-clickable once I've clicked on one band. Dev tools shows that the `rr-navbar` is overflowing the `rr-main-panel`.

<img width="807" alt="screen shot 2018-05-02 at 8 26 11 pm" src="https://user-images.githubusercontent.com/58702/39556641-54a00e82-4e47-11e8-93dc-65d9c35b2e37.png">

I don't find any CSS rules in the book that alters the `list-style` of the `ul` so I think maybe something is missing.

Here's my entire `app.css` if it helps:

```css
a {
  color: inherit;
  text-decoration: none;
}

.rr-container {
  margin-left: auto;
  margin-right: auto;
  width: 100%;
}

.rr-container::after {
  clear: both;
}

@media screen and (min-width: 60em) and (max-width: 100em) {
  .rr-container {
    width: 80%
  }
}

@media screen and (min-width: 100em) {
  .rr-container {
    width: 50%;
  }
}

.rr-page-header {
  padding-bottom: 9px;
  margin: 40px 0 20px;
  border-bottom: 1px solid;
}

.rr-header-link > .rr-app-title {
  margin-top: 0;
  margin-bottom: 0;
}
.rr-panel {
  padding: 1rem;
  border: .125rem solid;
  border-radius: .125rem;
}
.rr-textarea {
  width: 100%;
  padding: .5rem;
}

.rr-app-title > .rr-subtitle {
  font-weight: normal;
}

.list > li {
  margin-bottom: 10px;
}


:root {
  --bright-yellow: #ffda00;
  --navitem-link-color: var(--bright-yellow);
  --blue: #357edd;
  --dark-blue: #00449e;
  --light-blue: #96ccff;
  --mid-grey: #555;
  --near-white: #f4f4f4;
  --input-color: var(--mid-grey);
  --button-color: var(--near-white);
  --button-bg-color: var(--blue);
  --button-hover-color: var(--dark-blue);
  --button-disabled-color: var(--light-blue);
}

.rr-navbar {
  position: relative;
  min-height: 50px;
  border: 1px solid transparent;
}

.rr-navbar > .rr-nav {
  display: flex;
  margin: 0;
  padding: 0;
  list-style-type: none;
}

.rr-navbar-item {
  padding: 5px;
}

.rr-navbar-item > a:hover {
  border-bottom: 2px solid var(--navitem-link-color);
}

.rr-navbar-item > a.active {
  color: inherit;
  border-bottom: 2px solid var(--navitem-link-color);
}

.rr-navbar-item + .rr-navbar-item {
  margin-left: 10px;
}

.rr-sidebar {
  float: left;
  width: calc( 100% / 3 ); /* .w-third */
};

.rr-main-panel {
  float: left;
  width: calc( 100% / 1.5); /* .w-two-thirds */
}

.rr-list {
  list-style-type: none;
  padding-left: 1rem;
  margin: 0;
}

.rr-list-item {
  margin-bottom: 10px;
}

.rr-empty-message {
  text-align: center;
}

.rr-band-link > .rr-pointer {
  margin-left: 5px;
  display: none;
}

.rr-band-link.active > .rr-pointer {
  display: inline-block;
}


.rr-new-label {
  margin-top: 1rem;
  padding-left: 1rem;
}

.rr-input {
  color: var(--input-color);
  border-style: solid;
  border-width: 1px;
  padding: .25rem;
}

.rr-action-button {
  color: var(--button-color);
  background-color: var(--button-bg-color);
  border-radius: .125rem;
  padding: .25rem;
  padding-left: .5rem;
  padding-right: .5rem;
}

.rr-action-button:hover {
  background-color: var(--button-hover-color);
}

.rr-action-button[disabled] {
  background-color: var(--button-disabled-color);
}

.rr-cancel-icon {
  align-self: center;
  margin-left: .25rem;
}

.rr-inline-form {
  display: flex;
}

.rr-inline-form-group {
  display: flex;
  justify-content: space-between;
}
```

**Comment by jagthedrummer** [comment]
Ah-ha! I just discovered that the code snippet on page 125 contains `<ul class="nav">` which should be `<ul class="rr-nav">`. Making that change gets the links to sit side-by-side and be styled correctly.

And removing `position: relative;` from the `.rr-navbar` block fixes the overflow problem.

```css
.rr-navbar {
  /*position: relative;*/
  min-height: 50px;
  border: 1px solid transparent;
}
```

**Comment by jagthedrummer** [comment]
There's also some overflow funkiness with the description:

<img width="1080" alt="screen shot 2018-05-02 at 8 44 44 pm" src="https://user-images.githubusercontent.com/58702/39556947-bb40cfda-4e49-11e8-83fb-0abe2f51f7ba.png">

**Comment by jagthedrummer** [comment]
Also related:

<img width="1105" alt="screen shot 2018-05-02 at 8 49 33 pm" src="https://user-images.githubusercontent.com/58702/39557048-6d11519e-4e4a-11e8-8b75-7614c3241637.png">

I guess the `rr-main-panel` isn't being constrained correctly...

**Comment by jagthedrummer** [comment]
Ah, found it! On page 51 there's an extra `;` after the block for `rr-sidebar`:

```css
.rr-sidebar {
  float: left;
  width: calc( 100% / 3 ); /* .w-third */
};
```
