### ISSUE TITLE
Convert rating stars to be spans

### ISSUE THREAD

**Issue by balinterdi** [balinterdi/rarwe-issues#324]
And add the following CSS rule to still have a pointer cursor:

```css
.rating-panel > .rating-star {
  cursor: pointer;
}
```
