### ISSUE TITLE
Component chapter className inconsistency

### ISSUE THREAD

**Issue by jourdy345** [balinterdi/rarwe-issues#53]
The CSS says .rating-star whereas the components/star-rating.hbs says .star-rating, resulting in not producing the intended CSS effect.

//app.css
```CSS
.rating-star { float: left; margin-left: 3px;
}
```
//components/star-rating.hbs
```HTML
{{#each stars as |star|}}
  <span class="star-rating glyphicon {{if star.full 'glyphicon-star' 'glyphicon-star-empty'}}" {{action "set" star.rating}}>
  </span>
{{/each}}
```
